apiVersion: apps/v1
kind: Deployment
metadata:
  name: autossh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autossh
  template:
    metadata:
      labels:
        app: autossh
    spec:
      serviceAccountName: ssh-key-creator
      initContainers:
      - name: wait-for-secret
        image: alpine:latest
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache kubectl
          until kubectl get secret ssh-key; do
            echo "Waiting for ssh-key secret..."
            sleep 5
          done
      containers:
      - name: autossh
        image: jnovack/autossh:latest
        env:
        - name: SSH_REMOTE_HOST
          value: "ssh.external.wg.dphx.eu"
        - name: SSH_REMOTE_PORT
          value: "4022"
        - name: SSH_REMOTE_USER
          value: "ineb01"
        - name: SSH_TUNNEL_REMOTE
          value: "2049"
        - name: SSH_TUNNEL_LOCAL
          value: "2049"
        - name: SSH_TUNNEL_HOST
          value: "0.0.0.0"
        - name: SSH_HOSTKEY_VERIFICATION
          value: "false"
        ports:
        - containerPort: 2049
          name: nfs
        volumeMounts:
        - name: ssh-key
          mountPath: /id_rsa
          subPath: id_rsa
          readOnly: true
        securityContext:
          runAsUser: 0
      volumes:
      - name: ssh-key
        secret:
          secretName: ssh-key
          defaultMode: 0600
---
apiVersion: v1
kind: Service
metadata:
  name: autossh-service
spec:
  selector:
    app: autossh
  ports:
  - port: 2049
    targetPort: 2049
    name: nfs
