apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.43.234.216
    path: /home/public
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
