apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 127.0.0.1
    path: /home/public/Nextcloud
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
