apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: autossh-service.applications.svc.cluster.local
    path: /home/public
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
