apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
type: Opaque
data:
  # Base64 encoded SSH private key
  # Replace with: cat ~/.ssh/id_rsa | base64 -w 0
  id_rsa: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
